**O objetivo deste projeto consiste em puxar do site da CBF os dados referentes à tabela do brasileirão**

In [1]:
pip install requests

Requirement already satisfied: requests in c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages (from requests) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages (from requests) (2021.10.8)
Note: you may need to restart the kernel to use updated packages.

In [2]:
'''URL = https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-a'''

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
import requests

In [3]:
url = 'https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-a/2021'
#Object page
page = requests.get(url)

# parser-lxml = Change html to Python friendly format
# Obtain page's information
soup = bs(page.text, 'lxml')
soup

# Obtain information from tag <table>
table1 = soup.find('table',class_="table m-b-20 tabela-expandir")

# Obtain every title of columns with tag <th>

# Por conta da existencia de um <th> na <body>, o programa puxa a primeira coluna referente a pontos, portanto, precisamos usar um for para pegar apenas os 12 primeiros termos da <head>, que seria o cabeçalho. 
headers = []
cont = 0
for i in table1.find_all('th'):
 title = i.text
 cont = cont +1
 if cont<=12:
     headers.append(title)
#Adição do nome do time na segunda coluna
headers.insert(1, 'Time')

#Create a dataframe
mydata = pd.DataFrame(columns = headers)
mydata.head()

Empty DataFrame
Columns: [Posição, Time, PTS, J, V, E, D, GP, GC, SG, CA, CV, %]
Index: []

In [4]:
# Create a for loop to fill mydata
#Obtendo posições dos times
posicoes = []
for i in range(1,21):
    posicoes.append(str(i)+"°")
mydata['Posição']=posicoes

#Obtendo times
times = table1.find_all('span',class_="hidden-xs")
dict_times =[]
for i in range(len(times)):
    dict_times.append(times[i].text.split(" - ")[0].strip())
mydata['Time'] = dict_times
print(mydata)

   Posição                  Time  PTS    J    V    E    D   GP   GC   SG   CA  \
0       1°      Atlético Mineiro  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1       2°              Flamengo  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2       3°             Palmeiras  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3       4°             Fortaleza  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4       5°           Corinthians  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5       6°   Red Bull Bragantino  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6       7°            Fluminense  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7       8°               America  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8       9°              Atlético  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9      10°                Santos  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10     11°                 Ceará  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11     12°         Internacional  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12     13°             São Paulo  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13     14°  Athletico Paranaense  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14     15°                Cuiabá  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15     16°             Juventude  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16     17°                Grêmio  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17     18°                 Bahia  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
18     19°                 Sport  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19     20°           Chapecoense  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     CV    %
0   NaN  NaN
1   NaN  NaN
2   NaN  NaN
3   NaN  NaN
4   NaN  NaN
5   NaN  NaN
6   NaN  NaN
7   NaN  NaN
8   NaN  NaN
9   NaN  NaN
10  NaN  NaN
11  NaN  NaN
12  NaN  NaN
13  NaN  NaN
14  NaN  NaN
15  NaN  NaN
16  NaN  NaN
17  NaN  NaN
18  NaN  NaN
19  NaN  NaN

In [5]:
#Obtendo pontos
pontos = []
for i in table1.find_all('th')[14:]:
 pontos.append(i.text)
mydata['PTS'] = pontos
mydata

,Posição,Time,PTS,J,V,E,D,GP,GC,SG,CA,CV,%
0,1°,Atlético Mineiro,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2°,Flamengo,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3°,Palmeiras,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4°,Fortaleza,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5°,Corinthians,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6°,Red Bull Bragantino,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7°,Fluminense,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8°,America,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9°,Atlético,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10°,Santos,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11°,Ceará,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12°,Internacional,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13°,São Paulo,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14°,Athletico Paranaense,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15°,Cuiabá,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16°,Juventude,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17°,Grêmio,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18°,Bahia,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19°,Sport,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20°,Chapecoense,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Obtendo valores restantes
matrix = []
for j in table1.find_all('tr',class_="expand-trigger"):
 row_data = j.find_all('td')
 row = [i.text for i in row_data][1:11]
 matrix.append(row)

jogo = []
vitoria = []
empate = []
derrota = []
gp = []
gc = []
sg = []
ca = []
cv = []
porcent = []

for linha in range(len(matrix)):
        jogo.append(matrix[linha][0])
        vitoria.append(matrix[linha][1])
        empate.append(matrix[linha][2])
        derrota.append(matrix[linha][3])
        gp.append(matrix[linha][4])
        gc.append(matrix[linha][5])
        sg.append(matrix[linha][6])
        ca.append(matrix[linha][7])
        cv.append(matrix[linha][8])
        porcent.append(matrix[linha][9])
mydata['J'] = jogo
mydata['V'] = vitoria
mydata['E'] = empate
mydata['D'] = derrota
mydata['GP'] = gp
mydata['GC'] = gc
mydata['SG'] = sg
mydata['CA'] = ca
mydata['CV'] = cv
mydata['%'] = porcent

mydata

   Posição                  Time PTS   J   V   E   D  GP  GC   SG   CA  CV   %
0       1°      Atlético Mineiro  84  38  26   6   6  67  34   33   82   4  73
1       2°              Flamengo  71  38  21   8   9  69  36   33   82   4  62
2       3°             Palmeiras  66  38  20   6  12  58  43   15   87  11  57
3       4°             Fortaleza  58  38  17   7  14  44  45   -1   95   7  50
4       5°           Corinthians  57  38  15  12  11  40  36    4   61   3  50
5       6°   Red Bull Bragantino  56  38  14  14  10  55  46    9   95   3  49
6       7°            Fluminense  54  38  15   9  14  38  38    0   91   4  47
7       8°               America  53  38  13  14  11  41  37    4   66   2  46
8       9°              Atlético  53  38  13  14  11  33  36   -3   98   7  46
9      10°                Santos  50  38  12  14  12  35  40   -5  103   4  43
10     11°                 Ceará  50  38  11  17  10  39  38    1   90   5  43
11     12°         Internacional  48  38  12  12  14  44  42    2  106  11  42
12     13°             São Paulo  48  38  11  15  12  31  39   -8  100   7  42
13     14°  Athletico Paranaense  47  38  13   8  17  41  45   -4   90   6  41
14     15°                Cuiabá  47  38  10  17  11  34  37   -3   84   7  41
15     16°             Juventude  46  38  11  13  14  36  44   -8   93   4  40
16     17°                Grêmio  43  38  12   7  19  44  51   -7  110   7  37
17     18°                 Bahia  43  38  11  10  17  42  51   -9   94   5  37
18     19°                 Sport  38  38   9  11  18  24  37  -13   94   5  33
19     20°           Chapecoense  15  38   1  12  25  27  67  -40   82  10  13

In [7]:
#Transformando em .csv
mydata.to_csv('brasileirao2021.csv', index=False)

In [8]:
# Try to read csv
mydata2 = pd.read_csv('brasileirao2021.csv')
mydata2

   Posição                  Time  PTS   J   V   E   D  GP  GC  SG   CA  CV   %
0       1°      Atlético Mineiro   84  38  26   6   6  67  34  33   82   4  73
1       2°              Flamengo   71  38  21   8   9  69  36  33   82   4  62
2       3°             Palmeiras   66  38  20   6  12  58  43  15   87  11  57
3       4°             Fortaleza   58  38  17   7  14  44  45  -1   95   7  50
4       5°           Corinthians   57  38  15  12  11  40  36   4   61   3  50
5       6°   Red Bull Bragantino   56  38  14  14  10  55  46   9   95   3  49
6       7°            Fluminense   54  38  15   9  14  38  38   0   91   4  47
7       8°               America   53  38  13  14  11  41  37   4   66   2  46
8       9°              Atlético   53  38  13  14  11  33  36  -3   98   7  46
9      10°                Santos   50  38  12  14  12  35  40  -5  103   4  43
10     11°                 Ceará   50  38  11  17  10  39  38   1   90   5  43
11     12°         Internacional   48  38  12  12  14  44  42   2  106  11  42
12     13°             São Paulo   48  38  11  15  12  31  39  -8  100   7  42
13     14°  Athletico Paranaense   47  38  13   8  17  41  45  -4   90   6  41
14     15°                Cuiabá   47  38  10  17  11  34  37  -3   84   7  41
15     16°             Juventude   46  38  11  13  14  36  44  -8   93   4  40
16     17°                Grêmio   43  38  12   7  19  44  51  -7  110   7  37
17     18°                 Bahia   43  38  11  10  17  42  51  -9   94   5  37
18     19°                 Sport   38  38   9  11  18  24  37 -13   94   5  33
19     20°           Chapecoense   15  38   1  12  25  27  67 -40   82  10  13